### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by lazybuggy** [ManishaW/Reptile1400#1]
Get the main character to move, switch animations?

**Comment by lazybuggy** [comment]
@ManishaW should i be doing clicking as welll.. or is that part of your task?

**Comment by ManishaW** [comment]
um well there are different types of clicking...
Clicking to go to a certain spot on the scene
Clicking to go to a new area
Clicking on areas of the scene to trigger a comment from the character
Clicking an object to add to collectibles 
Clicking from collectibles to combine 
Clicking on collectibles to place on the scene/ give to character
Clicking on character (possibly) for a hint or something

**Comment by lazybuggy** [comment]
true, I'll do... 

- Clicking to go to a certain spot on the scene
- Clicking to go to a new area
- Clicking on areas of the scene to trigger a comment from the character
- Clicking on character (possibly) for a hint or something

and you do the rest?

**Comment by lazybuggy** [comment]
Closing this for now.. mostly done I think?
